"""empty message

Revision ID: 5de10afafd35
Revises: 9a4c7a47bb43
Create Date: 2024-06-14 13:31:59.009342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de10afafd35'
down_revision = '9a4c7a47bb43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_column('pop_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pop_data', sa.VARCHAR(length=140), nullable=False))

    # ### end Alembic commands ###
