"""regions table

Revision ID: 906dc6f5d58d
Revises: 
Create Date: 2024-10-31 18:14:46.191133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906dc6f5d58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('okato_id', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    # ### end Alembic commands ###
